// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90m5eCDX67v-seA3YniDDs9YtGhcIM1A',
    appId: '1:473712729503:web:723fb45757d6980e88b1aa',
    messagingSenderId: '473712729503',
    projectId: 'flutterfirebase-f6cce',
    authDomain: 'flutterfirebase-f6cce.firebaseapp.com',
    storageBucket: 'flutterfirebase-f6cce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpxXxH5gcR-4_rfKx_4GGQfneuJYA2Lk',
    appId: '1:473712729503:android:13935b6d102fdfa588b1aa',
    messagingSenderId: '473712729503',
    projectId: 'flutterfirebase-f6cce',
    storageBucket: 'flutterfirebase-f6cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDt_WblPQgViSfcMXua1czJmxQryAOv9c',
    appId: '1:473712729503:ios:a67c41b819c4050788b1aa',
    messagingSenderId: '473712729503',
    projectId: 'flutterfirebase-f6cce',
    storageBucket: 'flutterfirebase-f6cce.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDt_WblPQgViSfcMXua1czJmxQryAOv9c',
    appId: '1:473712729503:ios:a67c41b819c4050788b1aa',
    messagingSenderId: '473712729503',
    projectId: 'flutterfirebase-f6cce',
    storageBucket: 'flutterfirebase-f6cce.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotificationExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA90m5eCDX67v-seA3YniDDs9YtGhcIM1A',
    appId: '1:473712729503:web:190a88d42d8671f588b1aa',
    messagingSenderId: '473712729503',
    projectId: 'flutterfirebase-f6cce',
    authDomain: 'flutterfirebase-f6cce.firebaseapp.com',
    storageBucket: 'flutterfirebase-f6cce.firebasestorage.app',
  );
}
